version: '3.9'
services:
  seo-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: seo-worker
    ports:
      - '8787:8787'
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/seo-ecommerce/server/node_modules
      - /workspace/seo-ecommerce/view/node_modules
    environment:
      - CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_API_TOKEN
      - NODE_ENV=development
    command: npm run dev
