#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "mesh"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
scope = "deco"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "deco"
enable_workflows = true

[deco.integration]
description = "MCP App Mesh for Deco CMS"
friendlyName = "Mesh"
icon = "https://assets.decocache.com/mcp/24cfa17a-a0a8-40dc-9313-b4c3bdb63af6/mesh_v1.png"

[[deco.bindings]]
type = "mcp"
name = "DECONFIG"
integration_name = "@deco/deconfig"

[[migrations]]
tag = "v1"
new_classes = ["Workflow"]

[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = ["**/*.sql"]
