#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "docs"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco.cx"
routes = [
  { pattern = "docs.decocms.com", custom_domain = true },
]

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "deco.cx"
bindings = []
enable_workflows = true
local = false

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_WORKFLOW_DO"
class_name = "Workflow"