#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "seo-ecommercex"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

# Re-added for hosting workspace identification (previous removal caused deploy to switch workspace and fail domain update)
scope = "alfanet"

[assets]
directory = "./view-build"
binding = "ASSETS"

[vars]
PUBLIC_APP_ORIGIN = "https://seo-ecommercex.deco.page"
PUBLIC_SUPABASE_URL = "https://bekbempccbkuyrvjuygr.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_sbXikEupU9bvVBCsjv03pQ_NEem9va7"

[deco]
workspace = "alfanet"
bindings = []
enable_workflows = false
local = false

[[kv_namespaces]]
binding = "SEO_CACHE"
id = "e523c11ce4ee4c0c8771ac0bbe859f23"
preview_id = "e60f890a11fd4e408c66e26e75f38c2c"