#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "seo-ecommercex"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

# Re-added for hosting workspace identification (previous removal caused deploy to switch workspace and fail domain update)
scope = "alfanet"

[assets]
directory = "./view-build"
binding = "ASSETS"

[vars]
# Dummy placeholders for local development to satisfy schema validation
CF_DISPATCH_NAMESPACE = "dev-dispatch"
CF_ACCOUNT_ID = "dev-account"
CF_API_TOKEN = "dev-token"
SUPABASE_URL = "http://localhost/dev-supabase"
SUPABASE_SERVER_TOKEN = "dev-supa-token"
TURSO_GROUP_DATABASE_TOKEN = "dev-turso-token"
TURSO_ORGANIZATION = "dev-turso-org"
OPENROUTER_API_KEY = "dev-openrouter"
PUBLIC_APP_ORIGIN = "https://seo-ecommercex.deco.page"

[deco]
workspace = "alfanet"
bindings = []
enable_workflows = false
local = false