#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "seo-ecommerce"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "alfanet"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "alfanet"
bindings = []
enable_workflows = false
local = false