#:schema node_modules/wrangler/config-schema.json
compatibility_flags = ["nodejs_compat"]
name = "apps-outbound"
main = "main.ts"
compatibility_date = "2024-11-27"
services = [{ binding = "DECO_CHAT_API", service = "deco-chat-api" }]

[version_metadata]
binding = "CF_VERSION_METADATA"


[observability]
enabled = true
