#:schema node_modules/@deco/workers-runtime/config-schema.json
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
name = "contract"
scope = "deco"

[deco]
enable_workflows = true

[deco.integration]
description = "Smart Contract system for marketplace apps. Enables contract signing, authorization, and settlement of payments for app usage."
friendlyName = "Smart Contract"

[[migrations]]
tag = "v1"
new_classes = ["Workflow"]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"
