#:schema node_modules/wrangler/config-schema.json
compatibility_flags = ["nodejs_compat"]
name = "deco-chat-api"
main = "main.ts"
compatibility_date = "2024-11-27"
routes = [
  { pattern = "api.deco.chat", custom_domain = true },
  { pattern = "*/*", zone_name = "deco.page" },
]

[vars]
VITE_USE_LOCAL_BACKEND = false

[observability]
enabled = true

[[dispatch_namespaces]]
binding = "PROD_DISPATCHER"
namespace = "deco-chat-prod"
