#:schema node_modules/wrangler/config-schema.json
compatibility_flags = ["nodejs_compat"]
name = "deco-chat-api"
main = "main.ts"
compatibility_date = "2024-11-27"
routes = [
  { pattern = "api.deco.chat", custom_domain = true },
]

[vars]
SUPABASE_URL = "https://auth.deco.cx"
VITE_USE_LOCAL_BACKEND = false

# [[tail_consumers]]
# service = "hyperdx-tail"