# https://docs.github.com/en/actions

name: Cf-API-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deco-chat-api / prod / cloudflare
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: ./apps/api
        run: |
          npm install --legacy-peer-deps

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: './apps/api'
          secrets: |
            DATABASE_URL
            ACCEPTED_API_KEYS
            SUPABASE_SERVER_TOKEN
        env:
          ACCEPTED_API_KEYS: ${{ secrets.ACCEPTED_API_KEYS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_SERVER_TOKEN: ${{ secrets.WEBDRAW_SUPABASE_SERVER_TOKEN }}
