name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./apps/api
        run: |
          npm install --legacy-peer-deps

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "./apps/api"
          secrets: |
            SUPABASE_URL
            SUPABASE_SERVER_TOKEN
            TURSO_ORGANIZATION
            TURSO_GROUP_DATABASE_TOKEN
            CF_ACCOUNT_ID
            CF_API_TOKEN
            CF_DISPATCH_NAMESPACE
            RESEND_API_KEY
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVER_TOKEN: ${{ secrets.SUPABASE_SERVER_TOKEN }}
          TURSO_ORGANIZATION: ${{ secrets.TURSO_ORGANIZATION }}
          TURSO_GROUP_DATABASE_TOKEN: ${{ secrets.TURSO_GROUP_DATABASE_TOKEN }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_DISPATCH_NAMESPACE: "deco-chat-prod"
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
