name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deco CLI
        run: deno install -Ar -g -n deco jsr:@deco/cli -f

      - name: Install dependencies
        run: |
          cd docs
          bun install

      - name: Deploy
        run: |
          cd docs
          bun run deploy
        env:
          DECO_DEPLOY_TOKEN: ${{ secrets.DECO_DEPLOY_TOKEN }}
