name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/ai/**"
      - "packages/sdk/**"
      - "packages/runtime/**"

jobs:
  deploy:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./apps/api
        run: bun install

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      
      - name: Download secrets to .secrets.json
        run: bun run ci:download-secrets
        env:
          # this env is available for gcloud auth inside your script if needed
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
      
      - name: Upload secrets to Cloudflare in bulk
        working-directory: ./apps/api
        run: npx wrangler secret bulk .secrets.json
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "./apps/api"
          command: publish

      - name: Publish default apps
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: bun run ci:publish-default-apps
        env:
          DECO_TOKEN: ${{ secrets.DECO_TOKEN }}
          PROJECT: /deco/default
