name: Publish
on:
  push:
    branches:
      - main
    paths:
      - "packages/runtime/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Generate JSON schema
        run: cd ./packages/runtime && deno run -A scripts/generate-json-schema.ts

      - name: Publish package
        run: cd ./packages/runtime && deno install && deno publish --allow-slow-types
