name: Publish Runtime
on:
  push:
    branches:
      - main
      - runtime-npm
    paths:
      - "packages/runtime/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build package
        run: bun run build
        working-directory: packages/runtime

      - name: Check if version changed
        id: version-check
        run: |
          # Get the current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Try to get the published version from npm (will fail if package doesn't exist)
          PUBLISHED_VERSION=$(npm view @deco/workers-runtime version 2>/dev/null || echo "0.0.0")

          echo "Current version: $CURRENT_VERSION"
          echo "Published version: $PUBLISHED_VERSION"
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "version-changed=true" >> $GITHUB_OUTPUT
            echo "✅ Version changed ($PUBLISHED_VERSION → $CURRENT_VERSION), will publish"
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
            echo "⏭️ Version unchanged ($CURRENT_VERSION), skipping publish"
          fi
        working-directory: packages/runtime
      
      - name: Generate JSON schema
        run: cd ./packages/runtime && bun run scripts/generate-json-schema.ts

      - name: Publish to NPM
        if: steps.version-check.outputs.version-changed == 'true'
        run: bun publish
        working-directory: packages/runtime
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
