name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Run lint
        run: deno run lint

      - name: Run format
        run: deno run fmt --check

      - name: Run check
        env:
          DENO_V8_FLAGS: --max-old-space-size=16384
        run: deno run check

      - name: Run test
        run: deno test --no-check
