name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run format
        run: bun run fmt

      - name: Run type check
        run: bun run bun:check:types

      - name: Run test
        run: bun run test
